// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Document.proto

package org.myddd.vertx.document.api;

public interface DocumentDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.myddd.vertx.document.api.DocumentDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string mediaId = 2;</code>
   * @return The mediaId.
   */
  String getMediaId();
  /**
   * <code>string mediaId = 2;</code>
   * @return The bytes for mediaId.
   */
  com.google.protobuf.ByteString
      getMediaIdBytes();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string documentType = 4;</code>
   * @return The documentType.
   */
  String getDocumentType();
  /**
   * <code>string documentType = 4;</code>
   * @return The bytes for documentType.
   */
  com.google.protobuf.ByteString
      getDocumentTypeBytes();

  /**
   * <code>string md5 = 5;</code>
   * @return The md5.
   */
  String getMd5();
  /**
   * <code>string md5 = 5;</code>
   * @return The bytes for md5.
   */
  com.google.protobuf.ByteString
      getMd5Bytes();
}
