// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Document.proto

package org.myddd.vertx.document.api;

public interface NullableDocumentDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.myddd.vertx.document.api.NullableDocumentDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return Whether the null field is set.
   */
  boolean hasNull();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The enum numeric value on the wire for null.
   */
  int getNullValue();
  /**
   * <code>.google.protobuf.NullValue null = 1;</code>
   * @return The null.
   */
  com.google.protobuf.NullValue getNull();

  /**
   * <code>.org.myddd.vertx.document.api.DocumentDTO data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.org.myddd.vertx.document.api.DocumentDTO data = 2;</code>
   * @return The data.
   */
  DocumentDTO getData();
  /**
   * <code>.org.myddd.vertx.document.api.DocumentDTO data = 2;</code>
   */
  DocumentDTOOrBuilder getDataOrBuilder();

  public NullableDocumentDTO.KindCase getKindCase();
}
